"use client"

import { useEffect, useState } from "react"
import { X, Download } from "lucide-react"
import * as XLSX from "xlsx"

interface ExcelViewerModalProps {
  readonly fileUrl: string
  readonly docName: string
  readonly onClose: () => void
}

interface ParsedSheet {
  name: string
  html: string
}

export function ExcelViewerModal({ fileUrl, docName, onClose }: ExcelViewerModalProps) {
  const [sheets, setSheets] = useState<ParsedSheet[]>([])
  const [activeSheet, setActiveSheet] = useState(0)
  const [loading, setLoading] = useState(true)
  const [loadError, setLoadError] = useState(false)

  useEffect(() => {
    async function load() {
      try {
        const res = await fetch(`${fileUrl}?inline=1`)
        if (!res.ok) { setLoadError(true); return }
        const buf = await res.arrayBuffer()
        const workbook = XLSX.read(buf, { type: "array" })
        const parsed = workbook.SheetNames.map((name) => ({
          name,
          html: XLSX.utils.sheet_to_html(workbook.Sheets[name], { editable: false }),
        }))
        setSheets(parsed)
      } catch {
        setLoadError(true)
      } finally {
        setLoading(false)
      }
    }
    void load()
  }, [fileUrl])

  useEffect(() => {
    function onKey(e: KeyboardEvent) {
      if (e.key === "Escape") onClose()
    }
    window.addEventListener("keydown", onKey)
    return () => window.removeEventListener("keydown", onKey)
  }, [onClose])

  return (
    <div className="fixed inset-0 z-50 flex flex-col bg-black/90">
      {/* Header */}
      <div className="flex items-center justify-between gap-4 px-4 py-3 bg-gray-900 text-white shrink-0">
        <span className="text-sm font-medium text-gray-100 truncate">{docName}</span>
        <div className="flex items-center gap-2 shrink-0">
          <a
            href={fileUrl}
            download={docName}
            className="flex items-center gap-1.5 px-3 py-1.5 text-xs font-medium text-gray-300 hover:text-white hover:bg-white/10 rounded-lg transition-colors"
          >
            <Download size={14} />
            Download
          </a>
          <button
            type="button"
            onClick={onClose}
            className="flex items-center gap-1.5 px-3 py-1.5 text-xs font-medium text-gray-300 hover:text-white hover:bg-white/10 rounded-lg transition-colors"
          >
            <X size={14} />
            Close
          </button>
        </div>
      </div>

      {/* Sheet tabs */}
      {sheets.length > 1 && (
        <div className="flex gap-1 px-3 py-2 bg-gray-800 border-b border-gray-700 shrink-0 overflow-x-auto">
          {sheets.map((s, i) => (
            <button
              key={s.name}
              type="button"
              onClick={() => setActiveSheet(i)}
              className={`px-3 py-1 text-xs font-medium rounded transition-colors whitespace-nowrap ${
                i === activeSheet
                  ? "bg-white text-gray-900"
                  : "text-gray-300 hover:text-white hover:bg-white/10"
              }`}
            >
              {s.name}
            </button>
          ))}
        </div>
      )}

      {/* Content — explicit light-mode styles prevent dark-theme inheritance */}
      <div className="flex-1 overflow-auto" style={{ backgroundColor: '#ffffff', color: '#111827', colorScheme: 'light' }}>
        {loading && (
          <div className="flex items-center justify-center h-full">
            <p style={{ color: '#6b7280' }} className="text-sm">Loading…</p>
          </div>
        )}
        {loadError && (
          <div className="flex items-center justify-center h-full">
            <p style={{ color: '#9ca3af' }} className="text-sm">Failed to load file.</p>
          </div>
        )}
        {!loading && !loadError && sheets[activeSheet] && (
          <div className="p-4 min-w-max">
            <style>{`
              .excel-sheet table { border-collapse: collapse; font-size: 13px; font-family: sans-serif; background: #fff; }
              .excel-sheet td, .excel-sheet th { border: 1px solid #d1d5db; padding: 4px 8px; min-width: 80px; white-space: nowrap; color: #111827; background: #fff; }
              .excel-sheet tr:first-child td, .excel-sheet tr:first-child th { background: #f3f4f6; font-weight: 600; }
            `}</style>
            <div
              className="excel-sheet"
              // Content is generated by SheetJS from server-stored files — not user-injected HTML
              dangerouslySetInnerHTML={{ __html: sheets[activeSheet].html }}
            />
          </div>
        )}
      </div>
    </div>
  )
}
