"use client"

import { useEffect, useState } from "react"
import { X, Download } from "lucide-react"
import mammoth from "mammoth"

interface WordViewerModalProps {
  readonly fileUrl: string
  readonly docName: string
  readonly onClose: () => void
}

export function WordViewerModal({ fileUrl, docName, onClose }: WordViewerModalProps) {
  const [html, setHtml] = useState<string | null>(null)
  const [loading, setLoading] = useState(true)
  const [loadError, setLoadError] = useState(false)

  useEffect(() => {
    async function load() {
      try {
        const res = await fetch(`${fileUrl}?inline=1`)
        if (!res.ok) { setLoadError(true); return }
        const buf = await res.arrayBuffer()
        const result = await mammoth.convertToHtml({ arrayBuffer: buf })
        setHtml(result.value)
      } catch {
        setLoadError(true)
      } finally {
        setLoading(false)
      }
    }
    void load()
  }, [fileUrl])

  useEffect(() => {
    function onKey(e: KeyboardEvent) {
      if (e.key === "Escape") onClose()
    }
    window.addEventListener("keydown", onKey)
    return () => window.removeEventListener("keydown", onKey)
  }, [onClose])

  return (
    <div className="fixed inset-0 z-50 flex flex-col bg-black/90">
      {/* Header */}
      <div className="flex items-center justify-between gap-4 px-4 py-3 bg-gray-900 text-white shrink-0">
        <span className="text-sm font-medium text-gray-100 truncate">{docName}</span>
        <div className="flex items-center gap-2 shrink-0">
          <a
            href={fileUrl}
            download={docName}
            className="flex items-center gap-1.5 px-3 py-1.5 text-xs font-medium text-gray-300 hover:text-white hover:bg-white/10 rounded-lg transition-colors"
          >
            <Download size={14} />
            Download
          </a>
          <button
            type="button"
            onClick={onClose}
            className="flex items-center gap-1.5 px-3 py-1.5 text-xs font-medium text-gray-300 hover:text-white hover:bg-white/10 rounded-lg transition-colors"
          >
            <X size={14} />
            Close
          </button>
        </div>
      </div>

      {/* Content — explicit light-mode styles prevent dark-theme inheritance */}
      <div className="flex-1 overflow-auto" style={{ backgroundColor: '#ffffff', color: '#111827', colorScheme: 'light' }}>
        {loading && (
          <div className="flex items-center justify-center h-full">
            <p style={{ color: '#6b7280' }} className="text-sm">Loading…</p>
          </div>
        )}
        {loadError && (
          <div className="flex items-center justify-center h-full">
            <p style={{ color: '#9ca3af' }} className="text-sm">Failed to load file.</p>
          </div>
        )}
        {!loading && !loadError && html !== null && (
          <div className="max-w-3xl mx-auto px-8 py-10">
            <style>{`
              .word-doc { font-family: Georgia, serif; font-size: 14px; line-height: 1.7; color: #111827; background: #fff; }
              .word-doc h1 { font-size: 1.6em; font-weight: 700; margin: 1em 0 0.4em; color: #111827; }
              .word-doc h2 { font-size: 1.3em; font-weight: 700; margin: 1em 0 0.4em; color: #111827; }
              .word-doc h3 { font-size: 1.1em; font-weight: 600; margin: 0.8em 0 0.3em; color: #111827; }
              .word-doc p  { margin: 0 0 0.7em; color: #111827; }
              .word-doc ul, .word-doc ol { margin: 0 0 0.7em 1.5em; color: #111827; }
              .word-doc li { margin-bottom: 0.25em; }
              .word-doc table { border-collapse: collapse; width: 100%; margin-bottom: 1em; }
              .word-doc td, .word-doc th { border: 1px solid #d1d5db; padding: 6px 10px; color: #111827; background: #fff; }
              .word-doc img { max-width: 100%; height: auto; }
              .word-doc strong { font-weight: 700; }
              .word-doc em { font-style: italic; }
            `}</style>
            <div
              className="word-doc"
              // Content is generated by mammoth from server-stored .docx files — not user-injected HTML
              dangerouslySetInnerHTML={{ __html: html }}
            />
          </div>
        )}
      </div>
    </div>
  )
}
